### ISSUE TITLE
Wrong set temperature is reported when in HEATING_8C merit a mode

### ISSUE THREAD

**Issue by ulfwin** [holgerpieta/Toshiba-AC-mqtt#4]
First of all, I'm very happy to find this repo, and thanks for making it available! I'm using Openhab for home automation, and there is no binding for Toshiba ACs yet. Currently I'm using a parallel Home Assistant install which forwards values over MQTT, which is not ideal. Also, I'm not able to set the Merit A features, which I'm hoping to accomplish here.

Trying it out I manage to set everything up, but it appears the temperature is set incorrectly when in the HEATING_8C mode. Only temperatures between 5 and 13 are possible, but in the below status print it shows up as 26 (is actually 10 in this example):
`2023-02-22 19:01:44,141:INFO:toshiba_ac.device: [AC Living Room] Current state: Status: ON, Mode: HEAT, Temperature: 26, FanMode: AUTO, SwingMode: NOT_USED, PowerSelection: POWER_100, MeritBFeature: OFF, MeritAFeature: HEATING_8C, AirPureIon: OFF, IndoorTemperature: 7, OutdoorTemperature: 2, Error: OK, Timer: TIMER6, RelativeHours: 0, RelativeMinutes: 0, SelfCleaning: OFF, LED: ON, Scheduler: UNKNOWN, UtcHours: 0, UtcMinutes: 0, IndoorHeatExchangerTemperature: NONE, IndoorPipeTemperature: NONE, IndoorFanRPM: NONE, CompressorOutletTemperature: NONE, CompressorInletTemperature: NONE, OutdoorHeatExchangerTemperature: NONE, CompressorFrequency: NONE, OutdoorFarnRPM: NONE, ValvePwmDutyCycle: NONE, IAC: NONE`

The same value is sent over MQTT.

It is clearly a symptom of the strange Toshiba interface, which shifts the meaning of the temperature depending on mode. What I don't get is that the code already is supposed to compensate for this. Here are the write and read methods respectively in device.py, where +16 and -16 is supposed to take care of it:
```
    async def send_state_to_ac(self, state):
        future_state = ToshibaAcFcuState.from_hex_state(self.fcu_state.encode())
        future_state.update(state.encode())

        # In SAVE mode reported temperatures are 16 degrees higher than actual setpoint (only when heating)
        if state.ac_temperature not in [ToshibaAcFcuState.AcTemperature.NONE, ToshibaAcFcuState.AcTemperature.UNKNOWN]:
            if future_state.ac_mode == ToshibaAcFcuState.AcMode.HEAT:
                if future_state.ac_merit_a_feature == ToshibaAcFcuState.AcMeritAFeature.HEATING_8C:
                    state.ac_temperature = ToshibaAcFcuState.AcTemperature(state.ac_temperature.value + 16)
```

```
    @property
    def ac_temperature(self):
        # In SAVE mode reported temperatures are 16 degrees higher than actual setpoint (only when heating)

        ret = self.fcu_state.ac_temperature

        if self.fcu_state.ac_mode == ToshibaAcFcuState.AcMode.HEAT:
            if self.fcu_state.ac_merit_a_feature == ToshibaAcFcuState.AcMeritAFeature.HEATING_8C:
                if self.fcu_state.ac_temperature not in [ToshibaAcFcuState.AcTemperature.NONE, ToshibaAcFcuState.AcTemperature.UNKNOWN]:
                    ret = ToshibaAcFcuState.AcTemperature(self.fcu_state.ac_temperature.value - 16)
```

I can find a way to fix this in a dirty way in the top-script, but I thought I check with you first if there is a better fix.

Thanks in advance!

**Comment by holgerpieta** [comment]
Hey, nice that there are actually people using it.

Anyway, I've never tested that 8° heating mode, so I'm not surprised that it doesn't work properly.

The issue is caused by directly using `fcu_state.__str__()` and `fcu_state.forJson()` instead of going over the device functions.

I've pushed a new branch: https://github.com/holgerpieta/Toshiba-AC-mqtt/tree/heat8deg
which moves forJson() vom fcu_state to device.

Unfortunately I cannot easily test it in the moment, so it might just explode. If you can, please give it a go and see if it works at all and if yes, if it fixes anything. Or makes it even worse.

**Comment by ulfwin** [comment]
Great! I'll try it out and come back to you

**Comment by ulfwin** [comment]
Unfortunately it does not seem to work. For some strange reason I now get the following error:
```
python toshiba_ac_to_mqtt.py 
2023-02-28 19:47:11,751:WARNING:mqtt: unfiltered_messages() is deprecated and will be removed in a future version. Use messages() instead.
2023-02-28 19:47:11,753:ERROR:toshiba_ac.device_manager: Something failed while connecting: mobileapi.toshibahomeaccontrols.com/api/Consumer/Login
Traceback (most recent call last):
  File "/opt/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 52, in connect
    await self.http_api.connect()
  File "/opt/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 104, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
  File "/opt/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 85, in request_api
    async with method() as response:
  File "/opt/python3-toshiba-ac-mqtt-venv/lib/python3.7/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/opt/python3-toshiba-ac-mqtt-venv/lib/python3.7/site-packages/aiohttp/client.py", line 529, in _request
    traces=traces,
  File "/opt/python3-toshiba-ac-mqtt-venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/opt/python3-toshiba-ac-mqtt-venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: mobileapi.toshibahomeaccontrols.com/api/Consumer/Login
2023-02-28 19:47:11,767:WARNING:toshiba_ac.device_manager: Shutting down
```

I've tried switching back and fourth, to make sure it's not a temporary outage of the API. I'll look a bit closer at this and see if I figure something out...

**Comment by holgerpieta** [comment]
Ah, stupid, I used a working copy that wasn't up to the date and so the heat8deg branch was behind main by two critical commits. I forced pushed the branch again, rebased on current main.
Please try again.

**Comment by ulfwin** [comment]
Still don't understand the url error, but simply moving the forJson method to device.py will not work I think, since the members of that class are not the same (and you're using `vars`). Maybe using `self.fcu_state` instead could work?

Then again the state is probably saved as the higher value, so I'm thinking it has to go through the `ac_temperature` method...

**Comment by ulfwin** [comment]
> Ah, stupid, I used a working copy that wasn't up to the date and so the heat8deg branch was behind main by two critical commits. I forced pushed the branch again, rebased on current main. Please try again.

Aha! Great, that explains it :)

**Comment by holgerpieta** [comment]
Now I'm confused. Does it work now or do you get errors because `forJSON()` tries to access stuff that's not there?

**Comment by ulfwin** [comment]
I think there is still an issue as I mentioned above, even if the URL now is correct, but I'll have to give it a try. Hopefully I get time tomorrow

**Comment by holgerpieta** [comment]
I found some time to test it and of course it did not work because I missed something. I fixed it and there is a new commit in the heat8deg branch.
Please test it. At least for me it worked (switching on and off and setting the louver position), so I'm somewhat optimistic that it will work for you, too. Though I still did not test the 8 deg heating mode. So that's up to you to find out if we've managed to fix that.

**Comment by ulfwin** [comment]
Just tried it, but unfortunately the temperature is still wrong. The reason is that the state saved in `self.fcu_state_delta` is the raw value from the API. To get the correction, `dev.ac_temperature` must be used to fetch the data. 

I've played around a bit and actually got it working (although I'm sure there are better ways to do it)

The problem is that I made some other changes as well, which you probably don't want, such as assigning one MQTT topic for each property, rather than one for the whole device.

In any case, this is how my `state_update` coroutine looks like in `toshiba_ac_to_mqtt`:
```
        # Send updated state to MQTT
        async def state_update( dev, state ):
            state_flt = state.get_all_as_list()
            if state_flt:
                for param_name in state_flt:

                    if hasattr(dev, param_name):
                        param_val = getattr(dev, param_name)

                        # Get name of parameter unless temperature (which is int)
                        if type(param_val) != int:
                            param_val = param_val.name

                        topic = f'{topic_root}/{dev.name}/{param_name.replace("ac_", "")}/{status_suffix}'
                        logger.debug( f'Sending MQTT status update with topic {topic}: {param_val}' )
                        await client.publish( topic, param_val, 2 )
```
Instead of using your `forJson`, I created a similar method called `get_all_as_list` that only returns the names of the properties, not the values. The values are then queried using the intended attribute (which includes the fix for temperature).

If you want I could extract only the change related to correcting the temp, and you can check if it's worth to pull in?

One thing to note, however, is that not all of the parameters you are posting is supported this way, since there is no attribute for it in device.py. For example RelativeHours and RelativeMinutes

**Comment by ulfwin** [comment]
I created a fork with my changes, in case someone want to do something similar:
https://github.com/ulfwin/Toshiba-AC-mqtt
